// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/analysis/analysis.proto

package analysis

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_RUB                  Currency = 1
	Currency_EUR                  Currency = 2
	Currency_USD                  Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "RUB",
		2: "EUR",
		3: "USD",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"RUB":                  1,
		"EUR":                  2,
		"USD":                  3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analysis_analysis_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_proto_analysis_analysis_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{0}
}

type SubscriptionType int32

const (
	SubscriptionType_TYPE_UNSPECIFIED SubscriptionType = 0
	SubscriptionType_STREAMING        SubscriptionType = 1 // Нетфликс, Яндекс Плюс, Спотифай
	SubscriptionType_SOFTWARE         SubscriptionType = 2 // JetBrains, ChatGPT Plus, Облако
	SubscriptionType_UTILITIES        SubscriptionType = 3 // ЖКХ, интернет, мобильная связь
	SubscriptionType_FINANCE          SubscriptionType = 4 // Кредиты, страховки, банковское обслуживание
	SubscriptionType_HEALTH           SubscriptionType = 5 // Фитнес-клуб, доставка здоровой еды, витамины
	SubscriptionType_EDUCATION        SubscriptionType = 6 // Курсы, онлайн-школы, подписки на книги
	SubscriptionType_OTHER            SubscriptionType = 7 // Всё остальное
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "STREAMING",
		2: "SOFTWARE",
		3: "UTILITIES",
		4: "FINANCE",
		5: "HEALTH",
		6: "EDUCATION",
		7: "OTHER",
	}
	SubscriptionType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"STREAMING":        1,
		"SOFTWARE":         2,
		"UTILITIES":        3,
		"FINANCE":          4,
		"HEALTH":           5,
		"EDUCATION":        6,
		"OTHER":            7,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analysis_analysis_proto_enumTypes[1].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_proto_analysis_analysis_proto_enumTypes[1]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{1}
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCurrency Currency               `protobuf:"varint,1,opt,name=total_currency,json=totalCurrency,proto3,enum=analysis.Currency" json:"total_currency,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThisMonth     bool                   `protobuf:"varint,3,opt,name=this_month,json=thisMonth,proto3" json:"this_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_proto_analysis_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatisticsRequest) GetTotalCurrency() Currency {
	if x != nil {
		return x.TotalCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *GetStatisticsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetStatisticsRequest) GetThisMonth() bool {
	if x != nil {
		return x.ThisMonth
	}
	return false
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSum      string         `protobuf:"bytes,1,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	PaymentsList  []*PaymentList `protobuf:"bytes,2,rep,name=payments_list,json=paymentsList,proto3" json:"payments_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_proto_analysis_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatisticsResponse) GetTotalSum() string {
	if x != nil {
		return x.TotalSum
	}
	return ""
}

func (x *GetStatisticsResponse) GetPaymentsList() []*PaymentList {
	if x != nil {
		return x.PaymentsList
	}
	return nil
}

type PaymentList struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PaymentsType SubscriptionType       `protobuf:"varint,1,opt,name=payments_type,json=paymentsType,proto3,enum=analysis.SubscriptionType" json:"payments_type,omitempty"`
	TotalSum     string                 `protobuf:"bytes,2,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	SubscriptionsName []string               `protobuf:"bytes,3,rep,name=subscriptions_name,json=subscriptionsName,proto3" json:"subscriptions_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentList) Reset() {
	*x = PaymentList{}
	mi := &file_proto_analysis_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentList) ProtoMessage() {}

func (x *PaymentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentList.ProtoReflect.Descriptor instead.
func (*PaymentList) Descriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentList) GetPaymentsType() SubscriptionType {
	if x != nil {
		return x.PaymentsType
	}
	return SubscriptionType_TYPE_UNSPECIFIED
}

func (x *PaymentList) GetTotalSum() string {
	if x != nil {
		return x.TotalSum
	}
	return ""
}

func (x *PaymentList) GetSubscriptionsName() []string {
	if x != nil {
		return x.SubscriptionsName
	}
	return nil
}

type AddPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3,oneof" json:"date,omitempty"`
	Type     SubscriptionType       `protobuf:"varint,3,opt,name=type,proto3,enum=analysis.SubscriptionType" json:"type,omitempty"`
	Name     string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Currency Currency               `protobuf:"varint,5,opt,name=currency,proto3,enum=analysis.Currency" json:"currency,omitempty"`
	Price    float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentRequest) Reset() {
	*x = AddPaymentRequest{}
	mi := &file_proto_analysis_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentRequest) ProtoMessage() {}

func (x *AddPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *AddPaymentRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddPaymentRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *AddPaymentRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_TYPE_UNSPECIFIED
}

func (x *AddPaymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPaymentRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *AddPaymentRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextBillingAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=next_billing_at,json=nextBillingAt,proto3" json:"next_billing_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentResponse) Reset() {
	*x = AddPaymentResponse{}
	mi := &file_proto_analysis_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentResponse) ProtoMessage() {}

func (x *AddPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentResponse.ProtoReflect.Descriptor instead.
func (*AddPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *AddPaymentResponse) GetNextBillingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextBillingAt
	}
	return nil
}

var File_proto_analysis_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/analysis/analysis.proto\x12\banalysis\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x14GetStatisticsRequest\x129\n" +
	"\x0etotal_currency\x18\x01 \x01(\x0e2\x12.analysis.CurrencyR\rtotalCurrency\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"this_month\x18\x03 \x01(\bR\tthisMonth\"p\n" +
	"\x15GetStatisticsResponse\x12\x1b\n" +
	"\ttotal_sum\x18\x01 \x01(\tR\btotalSum\x12:\n" +
	"\rpayments_list\x18\x02 \x03(\v2\x15.analysis.PaymentListR\fpaymentsList\"\x9a\x01\n" +
	"\vPaymentList\x12?\n" +
	"\rpayments_type\x18\x01 \x01(\x0e2\x1a.analysis.SubscriptionTypeR\fpaymentsType\x12\x1b\n" +
	"\ttotal_sum\x18\x02 \x01(\tR\btotalSum\x12-\n" +
	"\x12subscriptions_name\x18\x03 \x03(\tR\x11subscriptionsName\"\xf4\x01\n" +
	"\x11AddPaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x123\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04date\x88\x01\x01\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.analysis.SubscriptionTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12.\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x12.analysis.CurrencyR\bcurrency\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05priceB\a\n" +
	"\x05_date\"X\n" +
	"\x12AddPaymentResponse\x12B\n" +
	"\x0fnext_billing_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rnextBillingAt*?\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RUB\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03USD\x10\x03*\x87\x01\n" +
	"\x10SubscriptionType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTREAMING\x10\x01\x12\f\n" +
	"\bSOFTWARE\x10\x02\x12\r\n" +
	"\tUTILITIES\x10\x03\x12\v\n" +
	"\aFINANCE\x10\x04\x12\n" +
	"\n" +
	"\x06HEALTH\x10\x05\x12\r\n" +
	"\tEDUCATION\x10\x06\x12\t\n" +
	"\x05OTHER\x10\a2\xac\x01\n" +
	"\x0fAnalysisService\x12P\n" +
	"\rGetStatistics\x12\x1e.analysis.GetStatisticsRequest\x1a\x1f.analysis.GetStatisticsResponse\x12G\n" +
	"\n" +
	"AddPayment\x12\x1b.analysis.AddPaymentRequest\x1a\x1c.analysis.AddPaymentResponseB<Z:github.com/PavlentiyGo/notification-service/proto/analysisb\x06proto3"

var (
	file_proto_analysis_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_analysis_proto_rawDescData []byte
)

func file_proto_analysis_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_analysis_proto_rawDesc), len(file_proto_analysis_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_analysis_proto_rawDescData
}

var file_proto_analysis_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_analysis_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_analysis_analysis_proto_goTypes = []any{
	(Currency)(0),                 // 0: analysis.Currency
	(SubscriptionType)(0),         // 1: analysis.SubscriptionType
	(*GetStatisticsRequest)(nil),  // 2: analysis.GetStatisticsRequest
	(*GetStatisticsResponse)(nil), // 3: analysis.GetStatisticsResponse
	(*PaymentList)(nil),           // 4: analysis.PaymentList
	(*AddPaymentRequest)(nil),     // 5: analysis.AddPaymentRequest
	(*AddPaymentResponse)(nil),    // 6: analysis.AddPaymentResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_analysis_analysis_proto_depIdxs = []int32{
	0, // 0: analysis.GetStatisticsRequest.total_currency:type_name -> analysis.Currency
	4, // 1: analysis.GetStatisticsResponse.payments_list:type_name -> analysis.PaymentList
	1, // 2: analysis.PaymentList.payments_type:type_name -> analysis.SubscriptionType
	7, // 3: analysis.AddPaymentRequest.date:type_name -> google.protobuf.Timestamp
	1, // 4: analysis.AddPaymentRequest.type:type_name -> analysis.SubscriptionType
	0, // 5: analysis.AddPaymentRequest.currency:type_name -> analysis.Currency
	7, // 6: analysis.AddPaymentResponse.next_billing_at:type_name -> google.protobuf.Timestamp
	2, // 7: analysis.AnalysisService.GetStatistics:input_type -> analysis.GetStatisticsRequest
	5, // 8: analysis.AnalysisService.AddPayment:input_type -> analysis.AddPaymentRequest
	3, // 9: analysis.AnalysisService.GetStatistics:output_type -> analysis.GetStatisticsResponse
	6, // 10: analysis.AnalysisService.AddPayment:output_type -> analysis.AddPaymentResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_analysis_analysis_proto_init() }
func file_proto_analysis_analysis_proto_init() {
	if File_proto_analysis_analysis_proto != nil {
		return
	}
	file_proto_analysis_analysis_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_analysis_proto_rawDesc), len(file_proto_analysis_analysis_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_analysis_proto_depIdxs,
		EnumInfos:         file_proto_analysis_analysis_proto_enumTypes,
		MessageInfos:      file_proto_analysis_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_analysis_proto = out.File
	file_proto_analysis_analysis_proto_goTypes = nil
	file_proto_analysis_analysis_proto_depIdxs = nil
}
