services:
  rabbitmq:
    image: rabbitmq:4.3.0-management
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  postgres:
    image: postgres:18-bookworm
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/postgres_data:/var/lib/postgresql
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
  subscription-service:
    build:
      context: .
      dockerfile: services/subscription/Dockerfile
    ports:
      - "5051:5051"
    env_file:
      - .env
    depends_on:
      - postgres
  api-service:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "5050:5050"
    env_file:
      - .env
  currency:
    build:
      context: .
      dockerfile: services/currency/Dockerfile
    ports:
      - "5052:5052"
  analysis-service:
    build:
      context: .
      dockerfile: services/analysis/Dockerfile
    ports:
      - "5053:5053"
    env_file:
      - .env