// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/currency/currency.proto

package currency

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentCurrencyRequest) Reset() {
	*x = GetCurrentCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentCurrencyRequest) ProtoMessage() {}

func (x *GetCurrentCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{0}
}

type GetCurrentCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	USD           float32                `protobuf:"fixed32,1,opt,name=USD,proto3" json:"USD,omitempty"`
	EUR           float32                `protobuf:"fixed32,2,opt,name=EUR,proto3" json:"EUR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentCurrencyResponse) Reset() {
	*x = GetCurrentCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentCurrencyResponse) ProtoMessage() {}

func (x *GetCurrentCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentCurrencyResponse) GetUSD() float32 {
	if x != nil {
		return x.USD
	}
	return 0
}

func (x *GetCurrentCurrencyResponse) GetEUR() float32 {
	if x != nil {
		return x.EUR
	}
	return 0
}

var File_proto_currency_currency_proto protoreflect.FileDescriptor

const file_proto_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/currency/currency.proto\x12\bcurrency\"\x1b\n" +
	"\x19GetCurrentCurrencyRequest\"@\n" +
	"\x1aGetCurrentCurrencyResponse\x12\x10\n" +
	"\x03USD\x18\x01 \x01(\x02R\x03USD\x12\x10\n" +
	"\x03EUR\x18\x02 \x01(\x02R\x03EUR2r\n" +
	"\x0fCurrencyService\x12_\n" +
	"\x12GetCurrentCurrency\x12#.currency.GetCurrentCurrencyRequest\x1a$.currency.GetCurrentCurrencyResponseB<Z:github.com/PavlentiyGo/notification-service/proto/currencyb\x06proto3"

var (
	file_proto_currency_currency_proto_rawDescOnce sync.Once
	file_proto_currency_currency_proto_rawDescData []byte
)

func file_proto_currency_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)))
	})
	return file_proto_currency_currency_proto_rawDescData
}

var file_proto_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_currency_currency_proto_goTypes = []any{
	(*GetCurrentCurrencyRequest)(nil),  // 0: currency.GetCurrentCurrencyRequest
	(*GetCurrentCurrencyResponse)(nil), // 1: currency.GetCurrentCurrencyResponse
}
var file_proto_currency_currency_proto_depIdxs = []int32{
	0, // 0: currency.CurrencyService.GetCurrentCurrency:input_type -> currency.GetCurrentCurrencyRequest
	1, // 1: currency.CurrencyService.GetCurrentCurrency:output_type -> currency.GetCurrentCurrencyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_currency_currency_proto_init() }
func file_proto_currency_currency_proto_init() {
	if File_proto_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_currency_proto_depIdxs,
		MessageInfos:      file_proto_currency_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_currency_proto = out.File
	file_proto_currency_currency_proto_goTypes = nil
	file_proto_currency_currency_proto_depIdxs = nil
}
