// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: subscription.proto

package subscription

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_CURRENCY_RUB         Currency = 1
	Currency_CURRENCY_EUR         Currency = 2
	Currency_CURRENCY_USD         Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_RUB",
		2: "CURRENCY_EUR",
		3: "CURRENCY_USD",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_RUB":         1,
		"CURRENCY_EUR":         2,
		"CURRENCY_USD":         3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_subscription_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

type SubscriptionType int32

const (
	SubscriptionType_SUBSCRIPTION_CATEGORY_UNSPECIFIED SubscriptionType = 0
	SubscriptionType_SUBSCRIPTION_CATEGORY_STREAMING   SubscriptionType = 1 // Нетфликс, Яндекс Плюс, Спотифай
	SubscriptionType_SUBSCRIPTION_CATEGORY_SOFTWARE    SubscriptionType = 2 // JetBrains, ChatGPT Plus, Облако
	SubscriptionType_SUBSCRIPTION_CATEGORY_UTILITIES   SubscriptionType = 3 // ЖКХ, интернет, мобильная связь
	SubscriptionType_SUBSCRIPTION_CATEGORY_FINANCE     SubscriptionType = 4 // Кредиты, страховки, банковское обслуживание
	SubscriptionType_SUBSCRIPTION_CATEGORY_HEALTH      SubscriptionType = 5 // Фитнес-клуб, доставка здоровой еды, витамины
	SubscriptionType_SUBSCRIPTION_CATEGORY_EDUCATION   SubscriptionType = 6 // Курсы, онлайн-школы, подписки на книги
	SubscriptionType_SUBSCRIPTION_CATEGORY_OTHER       SubscriptionType = 7 // Всё остальное
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "SUBSCRIPTION_CATEGORY_UNSPECIFIED",
		1: "SUBSCRIPTION_CATEGORY_STREAMING",
		2: "SUBSCRIPTION_CATEGORY_SOFTWARE",
		3: "SUBSCRIPTION_CATEGORY_UTILITIES",
		4: "SUBSCRIPTION_CATEGORY_FINANCE",
		5: "SUBSCRIPTION_CATEGORY_HEALTH",
		6: "SUBSCRIPTION_CATEGORY_EDUCATION",
		7: "SUBSCRIPTION_CATEGORY_OTHER",
	}
	SubscriptionType_value = map[string]int32{
		"SUBSCRIPTION_CATEGORY_UNSPECIFIED": 0,
		"SUBSCRIPTION_CATEGORY_STREAMING":   1,
		"SUBSCRIPTION_CATEGORY_SOFTWARE":    2,
		"SUBSCRIPTION_CATEGORY_UTILITIES":   3,
		"SUBSCRIPTION_CATEGORY_FINANCE":     4,
		"SUBSCRIPTION_CATEGORY_HEALTH":      5,
		"SUBSCRIPTION_CATEGORY_EDUCATION":   6,
		"SUBSCRIPTION_CATEGORY_OTHER":       7,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_proto_enumTypes[1].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_subscription_proto_enumTypes[1]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Price     int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency  Currency               `protobuf:"varint,3,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type      SubscriptionType       `protobuf:"varint,5,opt,name=type,proto3,enum=subscription.SubscriptionType" json:"type,omitempty"`
	BillingAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=billing_at,json=billingAt,proto3" json:"billing_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_CATEGORY_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetBillingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingAt
	}
	return nil
}

type CreateSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Price     int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency  Currency               `protobuf:"varint,3,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type      SubscriptionType       `protobuf:"varint,5,opt,name=type,proto3,enum=subscription.SubscriptionType" json:"type,omitempty"`
	BillingAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=billing_at,json=billingAt,proto3" json:"billing_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *CreateSubscriptionResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CreateSubscriptionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_CATEGORY_UNSPECIFIED
}

func (x *CreateSubscriptionResponse) GetBillingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingAt
	}
	return nil
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Subscriptions []*CreateSubscriptionResponse `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*CreateSubscriptionResponse {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

type ChangeTotalCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      Currency               `protobuf:"varint,1,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTotalCurrencyRequest) Reset() {
	*x = ChangeTotalCurrencyRequest{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTotalCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTotalCurrencyRequest) ProtoMessage() {}

func (x *ChangeTotalCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTotalCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ChangeTotalCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeTotalCurrencyRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type ChangeTotalCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      Currency               `protobuf:"varint,1,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTotalCurrencyResponse) Reset() {
	*x = ChangeTotalCurrencyResponse{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTotalCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTotalCurrencyResponse) ProtoMessage() {}

func (x *ChangeTotalCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTotalCurrencyResponse.ProtoReflect.Descriptor instead.
func (*ChangeTotalCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeTotalCurrencyResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type GetStatisticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCurrency Currency               `protobuf:"varint,1,opt,name=total_currency,json=totalCurrency,proto3,enum=subscription.Currency" json:"total_currency,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticRequest) Reset() {
	*x = GetStatisticRequest{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticRequest) ProtoMessage() {}

func (x *GetStatisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatisticRequest) GetTotalCurrency() Currency {
	if x != nil {
		return x.TotalCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *GetStatisticRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetStatisticRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetStatisticRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetStatisticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticResponse) Reset() {
	*x = GetStatisticResponse{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticResponse) ProtoMessage() {}

func (x *GetStatisticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatisticResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\fsubscription\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x02\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x122\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.subscription.SubscriptionTypeR\x04type\x129\n" +
	"\n" +
	"billing_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbillingAt\"\x92\x02\n" +
	"\x1aCreateSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x122\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.subscription.SubscriptionTypeR\x04type\x129\n" +
	"\n" +
	"billing_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbillingAt\"\x19\n" +
	"\x17GetSubscriptionsRequest\"j\n" +
	"\x18GetSubscriptionsResponse\x12N\n" +
	"\rsubscriptions\x18\x01 \x03(\v2(.subscription.CreateSubscriptionResponseR\rsubscriptions\"D\n" +
	"\x19DeleteSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\"\x1c\n" +
	"\x1aDeleteSubscriptionResponse\"P\n" +
	"\x1aChangeTotalCurrencyRequest\x122\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\"Q\n" +
	"\x1bChangeTotalCurrencyResponse\x122\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\"\xcb\x01\n" +
	"\x13GetStatisticRequest\x12=\n" +
	"\x0etotal_currency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\rtotalCurrency\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\",\n" +
	"\x14GetStatisticResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total*Z\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_RUB\x10\x01\x12\x10\n" +
	"\fCURRENCY_EUR\x10\x02\x12\x10\n" +
	"\fCURRENCY_USD\x10\x03*\xb2\x02\n" +
	"\x10SubscriptionType\x12%\n" +
	"!SUBSCRIPTION_CATEGORY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSUBSCRIPTION_CATEGORY_STREAMING\x10\x01\x12\"\n" +
	"\x1eSUBSCRIPTION_CATEGORY_SOFTWARE\x10\x02\x12#\n" +
	"\x1fSUBSCRIPTION_CATEGORY_UTILITIES\x10\x03\x12!\n" +
	"\x1dSUBSCRIPTION_CATEGORY_FINANCE\x10\x04\x12 \n" +
	"\x1cSUBSCRIPTION_CATEGORY_HEALTH\x10\x05\x12#\n" +
	"\x1fSUBSCRIPTION_CATEGORY_EDUCATION\x10\x06\x12\x1f\n" +
	"\x1bSUBSCRIPTION_CATEGORY_OTHER\x10\a2\x15\n" +
	"\x13SubscriptionServiceB@Z>github.com/PavlentiyGo/notification-service/proto/subscriptionb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_subscription_proto_goTypes = []any{
	(Currency)(0),                       // 0: subscription.Currency
	(SubscriptionType)(0),               // 1: subscription.SubscriptionType
	(*CreateSubscriptionRequest)(nil),   // 2: subscription.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),  // 3: subscription.CreateSubscriptionResponse
	(*GetSubscriptionsRequest)(nil),     // 4: subscription.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),    // 5: subscription.GetSubscriptionsResponse
	(*DeleteSubscriptionRequest)(nil),   // 6: subscription.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),  // 7: subscription.DeleteSubscriptionResponse
	(*ChangeTotalCurrencyRequest)(nil),  // 8: subscription.ChangeTotalCurrencyRequest
	(*ChangeTotalCurrencyResponse)(nil), // 9: subscription.ChangeTotalCurrencyResponse
	(*GetStatisticRequest)(nil),         // 10: subscription.GetStatisticRequest
	(*GetStatisticResponse)(nil),        // 11: subscription.GetStatisticResponse
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_subscription_proto_depIdxs = []int32{
	0,  // 0: subscription.CreateSubscriptionRequest.currency:type_name -> subscription.Currency
	1,  // 1: subscription.CreateSubscriptionRequest.type:type_name -> subscription.SubscriptionType
	12, // 2: subscription.CreateSubscriptionRequest.billing_at:type_name -> google.protobuf.Timestamp
	0,  // 3: subscription.CreateSubscriptionResponse.currency:type_name -> subscription.Currency
	1,  // 4: subscription.CreateSubscriptionResponse.type:type_name -> subscription.SubscriptionType
	12, // 5: subscription.CreateSubscriptionResponse.billing_at:type_name -> google.protobuf.Timestamp
	3,  // 6: subscription.GetSubscriptionsResponse.subscriptions:type_name -> subscription.CreateSubscriptionResponse
	0,  // 7: subscription.ChangeTotalCurrencyRequest.currency:type_name -> subscription.Currency
	0,  // 8: subscription.ChangeTotalCurrencyResponse.currency:type_name -> subscription.Currency
	0,  // 9: subscription.GetStatisticRequest.total_currency:type_name -> subscription.Currency
	12, // 10: subscription.GetStatisticRequest.since:type_name -> google.protobuf.Timestamp
	12, // 11: subscription.GetStatisticRequest.to:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		EnumInfos:         file_subscription_proto_enumTypes,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
