// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/subscription/subscription.proto

package subscription

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_RUB                  Currency = 1
	Currency_EUR                  Currency = 2
	Currency_USD                  Currency = 3
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "RUB",
		2: "EUR",
		3: "USD",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"RUB":                  1,
		"EUR":                  2,
		"USD":                  3,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_subscription_subscription_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_proto_subscription_subscription_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

type SubscriptionType int32

const (
	SubscriptionType_TYPE_UNSPECIFIED SubscriptionType = 0
	SubscriptionType_STREAMING        SubscriptionType = 1 // Нетфликс, Яндекс Плюс, Спотифай
	SubscriptionType_SOFTWARE         SubscriptionType = 2 // JetBrains, ChatGPT Plus, Облако
	SubscriptionType_UTILITIES        SubscriptionType = 3 // ЖКХ, интернет, мобильная связь
	SubscriptionType_FINANCE          SubscriptionType = 4 // Кредиты, страховки, банковское обслуживание
	SubscriptionType_HEALTH           SubscriptionType = 5 // Фитнес-клуб, доставка здоровой еды, витамины
	SubscriptionType_EDUCATION        SubscriptionType = 6 // Курсы, онлайн-школы, подписки на книги
	SubscriptionType_OTHER            SubscriptionType = 7 // Всё остальное
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "STREAMING",
		2: "SOFTWARE",
		3: "UTILITIES",
		4: "FINANCE",
		5: "HEALTH",
		6: "EDUCATION",
		7: "OTHER",
	}
	SubscriptionType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"STREAMING":        1,
		"SOFTWARE":         2,
		"UTILITIES":        3,
		"FINANCE":          4,
		"HEALTH":           5,
		"EDUCATION":        6,
		"OTHER":            7,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_subscription_subscription_proto_enumTypes[1].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_proto_subscription_subscription_proto_enumTypes[1]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{1}
}

type CreateSubscriptionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	User      *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Price     int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency  Currency               `protobuf:"varint,3,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type      SubscriptionType       `protobuf:"varint,5,opt,name=type,proto3,enum=subscription.SubscriptionType" json:"type,omitempty"`
	BillingAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=billing_at,json=billingAt,proto3" json:"billing_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_TYPE_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetBillingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingAt
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	SecondName    string                 `protobuf:"bytes,4,opt,name=second_name,json=secondName,proto3" json:"second_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetSecondName() string {
	if x != nil {
		return x.SecondName
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Price     int32                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency  Currency               `protobuf:"varint,3,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type      SubscriptionType       `protobuf:"varint,5,opt,name=type,proto3,enum=subscription.SubscriptionType" json:"type,omitempty"`
	BillingAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=billing_at,json=billingAt,proto3" json:"billing_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *CreateSubscriptionResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSubscriptionResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CreateSubscriptionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionResponse) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_TYPE_UNSPECIFIED
}

func (x *CreateSubscriptionResponse) GetBillingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingAt
	}
	return nil
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Subscriptions []*CreateSubscriptionResponse `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*CreateSubscriptionResponse {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{6}
}

type ChangeTotalCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      Currency               `protobuf:"varint,1,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTotalCurrencyRequest) Reset() {
	*x = ChangeTotalCurrencyRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTotalCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTotalCurrencyRequest) ProtoMessage() {}

func (x *ChangeTotalCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTotalCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ChangeTotalCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeTotalCurrencyRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type ChangeTotalCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      Currency               `protobuf:"varint,1,opt,name=currency,proto3,enum=subscription.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTotalCurrencyResponse) Reset() {
	*x = ChangeTotalCurrencyResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTotalCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTotalCurrencyResponse) ProtoMessage() {}

func (x *ChangeTotalCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTotalCurrencyResponse.ProtoReflect.Descriptor instead.
func (*ChangeTotalCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeTotalCurrencyResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type GetStatisticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCurrency Currency               `protobuf:"varint,1,opt,name=total_currency,json=totalCurrency,proto3,enum=subscription.Currency" json:"total_currency,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticRequest) Reset() {
	*x = GetStatisticRequest{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticRequest) ProtoMessage() {}

func (x *GetStatisticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticRequest) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatisticRequest) GetTotalCurrency() Currency {
	if x != nil {
		return x.TotalCurrency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *GetStatisticRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetStatisticRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetStatisticRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type GetStatisticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticResponse) Reset() {
	*x = GetStatisticResponse{}
	mi := &file_proto_subscription_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticResponse) ProtoMessage() {}

func (x *GetStatisticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subscription_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticResponse) Descriptor() ([]byte, []int) {
	return file_proto_subscription_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatisticResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_subscription_subscription_proto protoreflect.FileDescriptor

const file_proto_subscription_subscription_proto_rawDesc = "" +
	"\n" +
	"%proto/subscription/subscription.proto\x12\fsubscription\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\x19CreateSubscriptionRequest\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.subscription.UserR\x04user\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x122\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.subscription.SubscriptionTypeR\x04type\x129\n" +
	"\n" +
	"billing_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbillingAt\"s\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vsecond_name\x18\x04 \x01(\tR\n" +
	"secondName\"\x92\x02\n" +
	"\x1aCreateSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x05R\x05price\x122\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x122\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1e.subscription.SubscriptionTypeR\x04type\x129\n" +
	"\n" +
	"billing_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tbillingAt\"2\n" +
	"\x17GetSubscriptionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"j\n" +
	"\x18GetSubscriptionsResponse\x12N\n" +
	"\rsubscriptions\x18\x01 \x03(\v2(.subscription.CreateSubscriptionResponseR\rsubscriptions\"D\n" +
	"\x19DeleteSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\"\x1c\n" +
	"\x1aDeleteSubscriptionResponse\"P\n" +
	"\x1aChangeTotalCurrencyRequest\x122\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\"Q\n" +
	"\x1bChangeTotalCurrencyResponse\x122\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\bcurrency\"\xcb\x01\n" +
	"\x13GetStatisticRequest\x12=\n" +
	"\x0etotal_currency\x18\x01 \x01(\x0e2\x16.subscription.CurrencyR\rtotalCurrency\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12*\n" +
	"\x02to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\",\n" +
	"\x14GetStatisticResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total*?\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RUB\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02\x12\a\n" +
	"\x03USD\x10\x03*\x87\x01\n" +
	"\x10SubscriptionType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTREAMING\x10\x01\x12\f\n" +
	"\bSOFTWARE\x10\x02\x12\r\n" +
	"\tUTILITIES\x10\x03\x12\v\n" +
	"\aFINANCE\x10\x04\x12\n" +
	"\n" +
	"\x06HEALTH\x10\x05\x12\r\n" +
	"\tEDUCATION\x10\x06\x12\t\n" +
	"\x05OTHER\x10\a2\xe1\x01\n" +
	"\x13SubscriptionService\x12g\n" +
	"\x12CreateSubscription\x12'.subscription.CreateSubscriptionRequest\x1a(.subscription.CreateSubscriptionResponse\x12a\n" +
	"\x10GetSubscriptions\x12%.subscription.GetSubscriptionsRequest\x1a&.subscription.GetSubscriptionsResponseB@Z>github.com/PavlentiyGo/notification-service/proto/subscriptionb\x06proto3"

var (
	file_proto_subscription_subscription_proto_rawDescOnce sync.Once
	file_proto_subscription_subscription_proto_rawDescData []byte
)

func file_proto_subscription_subscription_proto_rawDescGZIP() []byte {
	file_proto_subscription_subscription_proto_rawDescOnce.Do(func() {
		file_proto_subscription_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)))
	})
	return file_proto_subscription_subscription_proto_rawDescData
}

var file_proto_subscription_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_subscription_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_subscription_subscription_proto_goTypes = []any{
	(Currency)(0),                       // 0: subscription.Currency
	(SubscriptionType)(0),               // 1: subscription.SubscriptionType
	(*CreateSubscriptionRequest)(nil),   // 2: subscription.CreateSubscriptionRequest
	(*User)(nil),                        // 3: subscription.User
	(*CreateSubscriptionResponse)(nil),  // 4: subscription.CreateSubscriptionResponse
	(*GetSubscriptionsRequest)(nil),     // 5: subscription.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),    // 6: subscription.GetSubscriptionsResponse
	(*DeleteSubscriptionRequest)(nil),   // 7: subscription.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),  // 8: subscription.DeleteSubscriptionResponse
	(*ChangeTotalCurrencyRequest)(nil),  // 9: subscription.ChangeTotalCurrencyRequest
	(*ChangeTotalCurrencyResponse)(nil), // 10: subscription.ChangeTotalCurrencyResponse
	(*GetStatisticRequest)(nil),         // 11: subscription.GetStatisticRequest
	(*GetStatisticResponse)(nil),        // 12: subscription.GetStatisticResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_proto_subscription_subscription_proto_depIdxs = []int32{
	3,  // 0: subscription.CreateSubscriptionRequest.user:type_name -> subscription.User
	0,  // 1: subscription.CreateSubscriptionRequest.currency:type_name -> subscription.Currency
	1,  // 2: subscription.CreateSubscriptionRequest.type:type_name -> subscription.SubscriptionType
	13, // 3: subscription.CreateSubscriptionRequest.billing_at:type_name -> google.protobuf.Timestamp
	0,  // 4: subscription.CreateSubscriptionResponse.currency:type_name -> subscription.Currency
	1,  // 5: subscription.CreateSubscriptionResponse.type:type_name -> subscription.SubscriptionType
	13, // 6: subscription.CreateSubscriptionResponse.billing_at:type_name -> google.protobuf.Timestamp
	4,  // 7: subscription.GetSubscriptionsResponse.subscriptions:type_name -> subscription.CreateSubscriptionResponse
	0,  // 8: subscription.ChangeTotalCurrencyRequest.currency:type_name -> subscription.Currency
	0,  // 9: subscription.ChangeTotalCurrencyResponse.currency:type_name -> subscription.Currency
	0,  // 10: subscription.GetStatisticRequest.total_currency:type_name -> subscription.Currency
	13, // 11: subscription.GetStatisticRequest.since:type_name -> google.protobuf.Timestamp
	13, // 12: subscription.GetStatisticRequest.to:type_name -> google.protobuf.Timestamp
	2,  // 13: subscription.SubscriptionService.CreateSubscription:input_type -> subscription.CreateSubscriptionRequest
	5,  // 14: subscription.SubscriptionService.GetSubscriptions:input_type -> subscription.GetSubscriptionsRequest
	4,  // 15: subscription.SubscriptionService.CreateSubscription:output_type -> subscription.CreateSubscriptionResponse
	6,  // 16: subscription.SubscriptionService.GetSubscriptions:output_type -> subscription.GetSubscriptionsResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_subscription_subscription_proto_init() }
func file_proto_subscription_subscription_proto_init() {
	if File_proto_subscription_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subscription_subscription_proto_rawDesc), len(file_proto_subscription_subscription_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subscription_subscription_proto_goTypes,
		DependencyIndexes: file_proto_subscription_subscription_proto_depIdxs,
		EnumInfos:         file_proto_subscription_subscription_proto_enumTypes,
		MessageInfos:      file_proto_subscription_subscription_proto_msgTypes,
	}.Build()
	File_proto_subscription_subscription_proto = out.File
	file_proto_subscription_subscription_proto_goTypes = nil
	file_proto_subscription_subscription_proto_depIdxs = nil
}
